
import re

import gradio as gr
import numpy as np
import matplotlib as mpl

from settings import settings
from svm_baseline import load_model, get_coefficients


MODEL = load_model(path=settings.SVM_BASELINE_PATH)
COEFS = get_coefficients(MODEL, top_k=settings.COEF_MAX_TOP_K)


def get_cutoffs(log_vals, n_steps=10):
    the_range = log_vals.max() - log_vals.min()
    return np.arange(log_vals.min() + (the_range / n_steps), log_vals.max(), the_range / (n_steps - 1))


LABEL_MAP = {'pos': 'AI', 'neg': 'Human'}

CUTOFFS = {'AI': get_cutoffs(np.array(list(COEFS['pos'].values()))),
           'Human': get_cutoffs(np.array(list(COEFS['neg'].values())))}

RGB_RED, RGB_GREEN = (1, 0, 0), (0, 1, 0)


def AI_score(text):
    _, ai_score = MODEL.predict_proba([text])[0]
    return ai_score


def find_cutoff(score, cutoffs):
    for idx, cutoff in enumerate(cutoffs):
        if score <= cutoff:
            return idx
    return len(cutoffs)


def get_suspect_tokens(text, include_color=True):
    TOKEN_RE = re.compile(r'[a-zA-Z]+')
    output = []
    last = 0
    for match in TOKEN_RE.finditer(text):
        start, end = match.span()
        # append interim
        if last != start != 0:
            output.append((text[last:start], None))
        # find feature
        word = text[start:end]
        target_label = cutoff = None
        for label in COEFS.keys():
            if word in COEFS[label]:
                target_label = LABEL_MAP[label]
        # find cutoff
        if target_label is not None:
            cutoff = find_cutoff(COEFS[label][word], CUTOFFS[target_label])
            output.append((text[start:end], (cutoff)))
        else:
            output.append((text[start:end], None))
        last = end            
    if last != len(text):
        output.append((text[last:], None))
    return output


def on_click(text):
    return round(AI_score(text), 4), get_suspect_tokens(text)


def generate_color_map():
    pass


def rgb2hex(r,g,b):
    return "#{:02x}{:02x}{:02x}".format(r,g,b)


with gr.Blocks(title="AI Detection Service") as DEMO:
    gr.Markdown(
        """
        # AI Detection Service

        This web provides an inference service to detect texts that are suspect to have been generated using a Large Language Model like OpenAI's ChatGPT.


        Copy the text to the input field below and click on the "Score" button on the right to obtain a confidence score that the text has been generated by an AI.
        """
    )
    with gr.Row():
        with gr.Column(scale=4):
            input_text = gr.Textbox(label="Input Text", placeholder="Enter your text here...")
        with gr.Column(variant="panel", scale=1, min_width=50):
            score_btn = gr.Button("Score")
            output_score = gr.Textbox(label="Confidence")
        with gr.Column(scale=4):
            highlighted_text = gr.HighlightedText(
                label="Analysis", 
                show_inline_category=False, show_legend=True, combine_adjacent=True, 
                color_map={"Human": mpl.colors.rgb2hex(RGB_RED + (0.1,), keep_alpha=True), 
                           "AI": mpl.colors.rgb2hex(RGB_RED + (0.8,), keep_alpha=True)})

        score_btn.click(fn=on_click, inputs=input_text, outputs=[output_score, highlighted_text])



if __name__ == '__main__':
    DEMO.launch()
