
PORT = 5050
SVM_DETECTOR__MAX_TOP_K = 0
SVM_DETECTOR__CUE_PERCENTILE_CUTOFF = 0.75
BATCH_SIZE = 5

[LANGUAGES.EN]
MODEL_TYPE = 'SVMDetector'

[LANGUAGES.EN.MODEL_SETTINGS]
MODEL_PATH = 'models/svm_baseline.skops'

[LANGUAGES.NL]
MODEL_TYPE = 'SVMDetector'

[LANGUAGES.NL.MODEL_SETTINGS]
MODEL_PATH = 'models/svm_baseline_nl.skops'