
import numpy as np
import gradio as gr

from .settings import settings
from .models import MODEL


def on_click(text):
    score = MODEL.model.score(text)
    sent_scores = MODEL.model.score_sentences(text)    
    return round(score, 4), sent_scores


with gr.Blocks(title="AI Detection Service") as demo:
    gr.Markdown(
        """
        # AI Detection Service

        This web provides an inference service to detect texts that are suspect to have been 
        generated using a Large Language Model like OpenAI's ChatGPT.

        Copy the text to the input field below and click on the "Score" button on the right 
        to obtain a confidence score that the text has been generated by an AI.
        """
    )
    with gr.Row():
        with gr.Column(scale=4):
            input_text = gr.Textbox(label="Input Text", placeholder="Enter your text here...")
        with gr.Column(variant="panel", scale=1, min_width=50):
            score_btn = gr.Button("Score")
            output_score = gr.Text(label="Confidence", interactive=False)
        with gr.Column(scale=4):
            highlighted_text = gr.HighlightedText(
                label="Analysis",
                show_legend=True, combine_adjacent=True, container=False)
            
        score_btn.click(fn=on_click, inputs=input_text, outputs=[output_score, highlighted_text])


if __name__ == '__main__':
    demo.launch()
