
import gradio as gr

from .models import MODEL


def on_click(text):
    scores = MODEL.model.score(text)
    return round(scores, 4)


with gr.Blocks(title="LLM Detect (simple)") as demo:
    gr.Markdown(
        """
        # AI Detection Service

        This web provides an inference service to detect texts that are suspect to have been 
        generated using a Large Language Model like OpenAI's ChatGPT.
        
        Copy the text to the input field below and click on the "Score" button on the right 
        to obtain a confidence score that the text has been generated by an AI.
        """
    )
    with gr.Row():
        with gr.Column(scale=3):
            input_text = gr.Textbox(label="Input Text", placeholder="Enter your text here...")
        with gr.Column(variant="panel", scale=1, min_width=100):
            score_btn = gr.Button("Score")
            output_score = gr.Textbox(label="Confidence")
        score_btn.click(fn=on_click, inputs=input_text, outputs=output_score)


if __name__ == '__main__':
    demo.launch()
